version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DATABASE_URI=mongodb://mongo:27017/nestjs
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
