name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your branch
  pull_request:
    branches:
      - main  # Adjust to your branch

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Install front-end dependencies
        run: |
          cd frontend
          npm install

      - name: Build front-end
        run: |
          cd frontend
          npm run build

  test_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Install front-end dependencies
        run: |
          cd frontend
          npm install

      - name: Run front-end tests
        run: |
          cd frontend
          npm test

  # deploy_frontend:
  #   runs-on: ubuntu-latest
  #   needs: test_frontend
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'  # Adjust to your Node.js version

  #     - name: Install front-end dependencies
  #       run: |
  #         cd frontend
  #         npm install

  #     - name: Deploy front-end
  #       run: |
  #         cd frontend
  #         npm run deploy
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication if needed

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust to your Python version

      - name: Install back-end dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build back-end
        run: |
          cd backend
          # Add your build commands here
          echo "Building the back-end..."

  test_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust to your Python version

      - name: Install back-end dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run back-end tests
        run: |
          cd backend
          pytest  # Adjust to your test command

  # deploy_backend:
  #   runs-on: ubuntu-latest
  #   needs: test_backend
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'  # Adjust to your Python version

  #     - name: Install back-end dependencies
  #       run: |
  #         cd backend
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Deploy back-end
  #       run: |
  #         cd backend
  #         # Add your deploy commands here
  #         echo "Deploying the back-end..."
  #       env:
  #         DEPLOYMENT_API_KEY: ${{ secrets.DEPLOYMENT_API_KEY }}  # Deployment API key or other secrets
