name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    name: Build Frontend
    uses: ./frontend/.github/workflows/frontend.yml@main

  build_backend:
    name: Build Backend
    needs: build_frontend
    uses: ./backend/.github/workflows/backend.yml@main

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: [build_frontend, build_backend]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Kubectl
  #       uses: azure/setup-kubectl@v1

  #     - name: Deploy to Kubernetes
  #       run: |
  #         kubectl apply -f k8s/deployment.yaml
  #         kubectl apply -f k8s/service.yaml
  #       env:
  #         KUBECONFIG: ${{ secrets.KUBECONFIG }}
